spring:
  datasource:
    # MySQL 주소
    url: jdbc:mysql://localhost:3306/word_tower?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    # MySQL 계정 아이디 (기본은 root)
    username: root
    # MySQL 계정 비밀번호 (본인이 설정한 비밀번호 입력)
    password: Wnstjr102!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      # 앱 실행 시점에 테이블을 자동으로 생성해주는 옵션
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect